extends Node
	
## This function get the player walk direction/vector. This is generated by wasd/arrow keys/ right stick
## it returns the vector normalized
func get_move_vector():
	var input_vector = Vector2.ZERO
	if Input.is_action_pressed("up"):
		input_vector.y -= 1
	if Input.is_action_pressed("down"):
		input_vector.y += 1
	if Input.is_action_pressed("left"):
		input_vector.x -= 1
	if Input.is_action_pressed("right"):
		input_vector.x += 1
	input_vector = input_vector.normalized()
	return input_vector
	
## This function get the player direction/look vector. This is generated by either the mouse position and the player position or the controller right stick
## it returns the vector normalized
func get_look_vector(player_position):
	# not sure how expensive it is to get viewport ( not sure if i call this everytime or store the viewport ) 
	var mouse_position = get_viewport().get_mouse_position()
	return (mouse_position - player_position).normalized() 
	
